development:
  adapter: postgresql
  encoding: utf8
  database: speedmathematics_development
  pool: 5
  username: tomkadwill
  password:

test:
  adapter: postgresql
  encoding: utf8
  database: speedmathematics_test
  pool: 5
  username: tomkadwill
  password: